### ISSUE TITLE
[BUG] ios onRecvNewMessages fail

### ISSUE THREAD

**Issue by OrrinHatch** [openimsdk/open-im-sdk-reactnative#47] opened 2024-10-30 08:08 UTC
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

The message reception works fine on Android, but iOS is unable to receive messages.

**Comment by lgz5689** [comment] 2024-10-31 02:03
Please update the sdk and server to the latest. If the problem still exists, please collect detailed logs so that we can better locate the problem.

**Comment by OrrinHatch** [comment] 2024-10-31 05:41
SDK version "open-im-sdk-rn": "3.8.1-rc.1",

**Comment by lgz5689** [comment] 2024-10-31 06:21
`onRecvNewMessages` is not triggered when a message is received, but is it possible to query messages via other apis?

**Comment by OrrinHatch** [comment] 2024-10-31 13:46
i don't understand object-c development, can not fix it
please fix it

**Comment by OrrinHatch** [comment] 2024-10-31 14:05
When I use onRecvNewMessage on IOS, I can successfully receive new messages

**Comment by lgz5689** [comment] 2024-11-01 02:06
Thank you. According to your description, we should already know where the problem is and we will fix it as soon as possible

**Comment by lgz5689** [comment] 2024-11-01 02:06
> When I use onRecvNewMessage on IOS, I can successfully receive new messages

Thank you. According to your description, we should already know where the problem is and we will fix it as soon as possible

**Comment by lgz5689** [comment] 2024-11-01 02:32
You can try using the content of this pr to confirm if the fix has been completed. However, it is expected that `onRecvNewMessages` will also be deprecated in the next version, please note

**Closed** 2024-11-06 02:20 UTC
